name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make MakeFile

     

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
       name: build
       path: build/
